config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'urls#index'

  resources :urls, only: %i[index create show], param: :url
  get ':short_url', to: 'urls#visit', as: :visit
  get '/getlinks/last10', to: 'api#getlinks'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
# frozen_string_literal: true

class Click < ApplicationRecord
  belongs_to :url

  validates :browser , presence: true
  validates :platform , presence: true
  
  scope :current_month, -> {where('created_at >= ?', Time.now.at_beginning_of_month)}
end

app/models/url.rb
class Url < ApplicationRecord
  has_many :clicks

  validates :original_url, presence: true
  validates :original_url, uniqueness: true, format: { with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix }
  validates :short_url, presence:true
  validates_length_of :short_url, minimum: 5, maximum: 5
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def getlinks
    @urls =  Url.all.order('created_at DESC').limit(10)
    render json:@urls, include: ['clicks']
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
require "browser"

class UrlsController < ApplicationController
  def index
    @url = Url.new
    @urls =  Url.all.order('created_at DESC').limit(10)
  end

  def create
    url =  params[:url];
    @url =Url.all
    keyCode = (0...5).map { (65 + rand(26)).chr }.join
    while (!@url.find_by(short_url: keyCode).nil?)
      keyCode = (0...5).map { (65 + rand(26)).chr }.join
    end
    @urls = Url.new(original_url: url[:original_url], short_url: keyCode, clicks_count: 0 )
    if @urls.save
      redirect_to root_path
    else
      flash[:notice] = 'Invalid Url, empty or invalid url formats are not allowed!'
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @url = Url.find_by(short_url: params[:url])
    if (@url)
      @clicks = @url.clicks.order('created_at ASC').current_month
      dailyClicks = Hash.new
      browser = Hash.new
      platform = Hash.new
      @clicks.each do |click|
        dailyClicks[click.created_at.to_s[...10]] = dailyClicks[click.created_at.to_s[...10]] ? dailyClicks[click.created_at.to_s[...10]] + 1 : 1
        browser[click.browser] = browser[click.browser] ? browser[click.browser] + 1 : 1
        platform[click.platform] = platform[click.platform] ? platform[click.platform] + 1 : 1
      end
      @daily_clicks = dailyClicks.map{ |key, value| [key, value] }
      @browsers_clicks = browser.map{ |key, value| [key, value] }
      @platform_clicks = platform.map{ |key, value| [key, value] }
    else
      render plain: '404 page not found!!...'
    end
  end

  def visit
    @message = 'redirect'
    browser = Browser.new(request.env["HTTP_USER_AGENT"])
    short_url =  params[:short_url]
    @url = Url.find_by(short_url: short_url)
    if (@url)
      @clicks = Click.new(url_id: @url.id, platform: browser.platform.name, browser: browser.name)
      if (@clicks.save)
        clickCount = @url.clicks.count
        @url.update(clicks_count: clickCount)
      else
        @message = 'Unable'
      end
    else
      @message = '404'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def clickConfirmationMessage(msg)
    ans = ''
    case msg
      when 'redirect'
        ans = 'Redirecting to page, if page doesnt open click on the link...'
      when '404'
        ans = "Error 404, Short link not found"
      when 'unable'
        ans = "Sorry, ther ewas an error trying to acces this link"
      else
        ans = 'nothing'
    end
    ans
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeyUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo">HeyURL!</a>
      </div>
    </nav>
    <div class="container my-2 px-4">
      <% flash.each do |type, msg| %>
        <div class="rounded shadow bg-info d-flex align-items-center rounded" id="hideMe">
            <div class="w-100 p-3">
                <p class="fs-4 text-white text-center m-0"><%= msg %></p>
            </div>
        </div>
      <% end %>
  </div>
    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/urls/index.html.erb
<div class="row">
  <div class="col m12">
    <%= form_with model:@url do |f| %>
      <div class="card">
        <div class="card-content">
          <div class="row">
            <div class="col m8 offset-m2 center-align">
              <span class="card-title">Create a new short URL</span>
            </div>
          </div>
          <div class="row">
            <div class="col m6 offset-m2">
              <%= f.text_field :original_url, class: 'validate form-control', placeholder: 'Your original URL here' , id:'urlinp' %>
            </div>
            <div class="col m2">
              <%= f.submit 'Shorten URL', class:'waves-effect waves-light btn text-white' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<table class="table highlight">
  <thead>
    <tr>
      <th scope="col">Short URL</th>
      <th scope="col">Original URL</th>
      <th scope="col">Created</th>
      <th scope="col">Clicks Count</th>
      <th scope="col">Stats</th>
    </tr>
  </thead>
  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <th scope="row"><a href="http://127.0.0.1:3000/<%= url.short_url %>" target="_blank"><%= "http://127.0.0.1:3000/" + url.short_url %></a></th>
        <td>
          <a href="<%= url.original_url %>">
            <% if url.original_url.length > 35 %>
              <%= url.original_url[...35] + '...' %>
            <% else %>
              <%= url.original_url %>
            <% end %>
          </a>
        </td>
        <td><%= url.created_at.to_s[...10] %></td>
        <td><%= url.clicks_count %></td>
        <td>
          <a href="<%= url_path(url.short_url) %>">
            <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
              <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
            </svg>
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/urls/show.html.erb
<div class="row">
  <div class="col s12">
    <ul class="card-panel collection with-header">
      <li class="collection-header">
        <h4>
          Stats for http://127.0.0.1:3000/<%= @url.short_url %>
        </h4>
      </li>
      <li class="collection-item">Created <%= @url.created_at.strftime('%b %d, %Y') %></li>
      <li class="collection-item">
        Original URL: <%= link_to @url.original_url %>
      </li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div id="total-clicks-chart"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s6">
    <div class="card-panel">
      <div id="platforms-chart"></div>
    </div>
  </div>

  <div class="col s6">
    <div class="card-panel">
      <div id="browsers-chart"></div>
    </div>
  </div>
</div>

<script>
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawCharts);

  function drawTotalClicksChart() {
    var data = google.visualization.arrayToDataTable([
      ['day', 'clicks'],
    ].concat(<%= raw @daily_clicks %>));

    var options = {
      title: 'total clicks',
      haxis: {
        title: 'day of month'
      },
      vaxis: {
        title: 'clicks'
      }
    };

    var chart = new google.visualization.AreaChart(
      document.getElementById('total-clicks-chart')
    );
    chart.draw(data, options);
  }

  function drawBrowsersChart() {
    var data = google.visualization.arrayToDataTable([
      ['browser', 'clicks'],
    ].concat(<%= raw @browsers_clicks %>));

    var options = {
      title: 'Browsers'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('browsers-chart')
    );
    chart.draw(data, options);
  }

  function drawPlatformsChart() {
    var data = google.visualization.arrayToDataTable([
      ['platform', 'clicks'],
    ].concat(<%= raw @platform_clicks %>));

    var options = {
      title: 'Platform'
    };

    var chart = new google.visualization.PieChart(
      document.getElementById('platforms-chart')
    );
    chart.draw(data, options);
  }

  function drawCharts() {
    drawTotalClicksChart();
    drawBrowsersChart();
    drawPlatformsChart();
  }
 </script>

app/views/urls/visit.html.erb
<div class="container text-center">
  <p class="fs-1">
    <%= clickConfirmationMessage(@message) %>
  </p>
  <% if @url %>
    <p id="timer" class="text-center fs-1 text-info">3</p>
    <a id='link' class="text-center link-info fs-2" href="<%= @url.original_url %>"><%= @url.original_url[..40] + '...' %> </a>
  <% end %>
</div>

<script>
  setTimeout(function(){ 
    window.open(document.getElementById('link').href, "_self");
  }, 3000);

  let count = 3;
  setInterval(function(){
    count--;
    document.getElementById('timer').textContent = count;
  }, 1000);
</script>